/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * BinanceRawOrderBookEntry
 */


public class BinanceRawOrderBookEntry implements Parcelable
{
	@SerializedName("price")
	private Double price = null;

	@SerializedName("quantity")
	private Double quantity = null;

	public BinanceRawOrderBookEntry() {
	}

	public BinanceRawOrderBookEntry price(Double price) {
		this.price = price;
		return this;
	}

	/**
	 * Get price
	 *
	 * @return price
	 **/
	@Schema(description = "")
	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public BinanceRawOrderBookEntry quantity(Double quantity) {
		this.quantity = quantity;
		return this;
	}

	/**
	 * Get quantity
	 *
	 * @return quantity
	 **/
	@Schema(description = "")
	public Double getQuantity() {
		return quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BinanceRawOrderBookEntry binanceRawOrderBookEntry = (BinanceRawOrderBookEntry) o;
		return Objects.equals(this.price, binanceRawOrderBookEntry.price) &&
				Objects.equals(this.quantity, binanceRawOrderBookEntry.quantity);
	}

	@Override
	public int hashCode() {
		return Objects.hash(price, quantity);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BinanceRawOrderBookEntry {\n");

		sb.append("    price: ").append(toIndentedString(price)).append("\n");
		sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}


	public void writeToParcel(Parcel out, int flags) {
		out.writeValue(price);
		out.writeValue(quantity);
	}

	public static final Parcelable.Creator<BinanceRawOrderBookEntry> CREATOR = new Parcelable.Creator<BinanceRawOrderBookEntry>()
	{
		public BinanceRawOrderBookEntry createFromParcel(Parcel in) {
			return new BinanceRawOrderBookEntry(in);
		}

		public BinanceRawOrderBookEntry[] newArray(int size) {
			return new BinanceRawOrderBookEntry[size];
		}
	};

	public int describeContents() {
		return 0;
	}

	BinanceRawOrderBookEntry(Parcel in) {
		price = (Double) in.readValue(null);
		quantity = (Double) in.readValue(null);
	}
}
