/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BinanceRawFuturesIncomeHistory
 */


public class BinanceRawFuturesIncomeHistory implements Parcelable {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("incomeType")
  private BinanceIncomeType incomeType = null;

  @SerializedName("income")
  private Double income = null;

  @SerializedName("asset")
  private String asset = null;

  @SerializedName("info")
  private String info = null;

  @SerializedName("time")
  private DateTime time = null;

  @SerializedName("transactionId")
  private String transactionId = null;

  @SerializedName("tradeId")
  private String tradeId = null;

  public BinanceRawFuturesIncomeHistory() {
  }
  public BinanceRawFuturesIncomeHistory symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public BinanceRawFuturesIncomeHistory incomeType(BinanceIncomeType incomeType) {
    this.incomeType = incomeType;
    return this;
  }

   /**
   * Get incomeType
   * @return incomeType
  **/
  @Schema(description = "")
  public BinanceIncomeType getIncomeType() {
    return incomeType;
  }

  public void setIncomeType(BinanceIncomeType incomeType) {
    this.incomeType = incomeType;
  }

  public BinanceRawFuturesIncomeHistory income(Double income) {
    this.income = income;
    return this;
  }

   /**
   * Get income
   * @return income
  **/
  @Schema(description = "")
  public Double getIncome() {
    return income;
  }

  public void setIncome(Double income) {
    this.income = income;
  }

  public BinanceRawFuturesIncomeHistory asset(String asset) {
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @Schema(description = "")
  public String getAsset() {
    return asset;
  }

  public void setAsset(String asset) {
    this.asset = asset;
  }

  public BinanceRawFuturesIncomeHistory info(String info) {
    this.info = info;
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  @Schema(description = "")
  public String getInfo() {
    return info;
  }

  public void setInfo(String info) {
    this.info = info;
  }

  public BinanceRawFuturesIncomeHistory time(DateTime time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @Schema(description = "")
  public DateTime getTime() {
    return time;
  }

  public void setTime(DateTime time) {
    this.time = time;
  }

  public BinanceRawFuturesIncomeHistory transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @Schema(description = "")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public BinanceRawFuturesIncomeHistory tradeId(String tradeId) {
    this.tradeId = tradeId;
    return this;
  }

   /**
   * Get tradeId
   * @return tradeId
  **/
  @Schema(description = "")
  public String getTradeId() {
    return tradeId;
  }

  public void setTradeId(String tradeId) {
    this.tradeId = tradeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BinanceRawFuturesIncomeHistory binanceRawFuturesIncomeHistory = (BinanceRawFuturesIncomeHistory) o;
    return Objects.equals(this.symbol, binanceRawFuturesIncomeHistory.symbol) &&
        Objects.equals(this.incomeType, binanceRawFuturesIncomeHistory.incomeType) &&
        Objects.equals(this.income, binanceRawFuturesIncomeHistory.income) &&
        Objects.equals(this.asset, binanceRawFuturesIncomeHistory.asset) &&
        Objects.equals(this.info, binanceRawFuturesIncomeHistory.info) &&
        Objects.equals(this.time, binanceRawFuturesIncomeHistory.time) &&
        Objects.equals(this.transactionId, binanceRawFuturesIncomeHistory.transactionId) &&
        Objects.equals(this.tradeId, binanceRawFuturesIncomeHistory.tradeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, incomeType, income, asset, info, time, transactionId, tradeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BinanceRawFuturesIncomeHistory {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    incomeType: ").append(toIndentedString(incomeType)).append("\n");
    sb.append("    income: ").append(toIndentedString(income)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    tradeId: ").append(toIndentedString(tradeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(symbol);
    out.writeValue(incomeType);
    out.writeValue(income);
    out.writeValue(asset);
    out.writeValue(info);
    out.writeValue(time);
    out.writeValue(transactionId);
    out.writeValue(tradeId);
  }

  BinanceRawFuturesIncomeHistory(Parcel in) {
    symbol = (String)in.readValue(null);
    incomeType = (BinanceIncomeType)in.readValue(BinanceIncomeType.class.getClassLoader());
    income = (Double)in.readValue(null);
    asset = (String)in.readValue(null);
    info = (String)in.readValue(null);
    time = (DateTime)in.readValue(DateTime.class.getClassLoader());
    transactionId = (String)in.readValue(null);
    tradeId = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<BinanceRawFuturesIncomeHistory> CREATOR = new Parcelable.Creator<BinanceRawFuturesIncomeHistory>() {
    public BinanceRawFuturesIncomeHistory createFromParcel(Parcel in) {
      return new BinanceRawFuturesIncomeHistory(in);
    }
    public BinanceRawFuturesIncomeHistory[] newArray(int size) {
      return new BinanceRawFuturesIncomeHistory[size];
    }
  };
}
