/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import io.swagger.annotations.ApiModelProperty;

/**
 * BrokerOefInvestmentProgram
 */

public class BrokerOefInvestmentProgram
{
	@SerializedName("feeEntrance")
	private Double feeEntrance = null;

	@SerializedName("feeExit")
	private Double feeExit = null;

	@SerializedName("feeManagement")
	private Double feeManagement = null;

	@SerializedName("balancingIpfsHash")
	private String balancingIpfsHash = null;

	@SerializedName("lastPeriod")
	private Period lastPeriod = null;

	@SerializedName("assetParts")
	private List<OefAssetPart> assetParts = null;

	@SerializedName("id")
	private UUID id = null;

	@SerializedName("managerAccountId")
	private UUID managerAccountId = null;

	@SerializedName("dateFrom")
	private DateTime dateFrom = null;

	@SerializedName("dateTo")
	private DateTime dateTo = null;

	@SerializedName("description")
	private String description = null;

	@SerializedName("isEnabled")
	private Boolean isEnabled = null;

	@SerializedName("investMinAmount")
	private Double investMinAmount = null;

	@SerializedName("investMaxAmount")
	private Double investMaxAmount = null;

	@SerializedName("ipfsHash")
	private String ipfsHash = null;

	@SerializedName("balance")
	private Double balance = null;

	public BrokerOefInvestmentProgram feeEntrance(Double feeEntrance) {
		this.feeEntrance = feeEntrance;
		return this;
	}

	/**
	 * Get feeEntrance
	 *
	 * @return feeEntrance
	 **/
	@ApiModelProperty(value = "")
	public Double getFeeEntrance() {
		return feeEntrance;
	}

	public void setFeeEntrance(Double feeEntrance) {
		this.feeEntrance = feeEntrance;
	}

	public BrokerOefInvestmentProgram feeExit(Double feeExit) {
		this.feeExit = feeExit;
		return this;
	}

	/**
	 * Get feeExit
	 *
	 * @return feeExit
	 **/
	@ApiModelProperty(value = "")
	public Double getFeeExit() {
		return feeExit;
	}

	public void setFeeExit(Double feeExit) {
		this.feeExit = feeExit;
	}

	public BrokerOefInvestmentProgram feeManagement(Double feeManagement) {
		this.feeManagement = feeManagement;
		return this;
	}

	/**
	 * Get feeManagement
	 *
	 * @return feeManagement
	 **/
	@ApiModelProperty(value = "")
	public Double getFeeManagement() {
		return feeManagement;
	}

	public void setFeeManagement(Double feeManagement) {
		this.feeManagement = feeManagement;
	}

	public BrokerOefInvestmentProgram balancingIpfsHash(String balancingIpfsHash) {
		this.balancingIpfsHash = balancingIpfsHash;
		return this;
	}

	/**
	 * Get balancingIpfsHash
	 *
	 * @return balancingIpfsHash
	 **/
	@ApiModelProperty(value = "")
	public String getBalancingIpfsHash() {
		return balancingIpfsHash;
	}

	public void setBalancingIpfsHash(String balancingIpfsHash) {
		this.balancingIpfsHash = balancingIpfsHash;
	}

	public BrokerOefInvestmentProgram lastPeriod(Period lastPeriod) {
		this.lastPeriod = lastPeriod;
		return this;
	}

	/**
	 * Get lastPeriod
	 *
	 * @return lastPeriod
	 **/
	@ApiModelProperty(value = "")
	public Period getLastPeriod() {
		return lastPeriod;
	}

	public void setLastPeriod(Period lastPeriod) {
		this.lastPeriod = lastPeriod;
	}

	public BrokerOefInvestmentProgram assetParts(List<OefAssetPart> assetParts) {
		this.assetParts = assetParts;
		return this;
	}

	public BrokerOefInvestmentProgram addAssetPartsItem(OefAssetPart assetPartsItem) {
		if (this.assetParts == null) {
			this.assetParts = new ArrayList<OefAssetPart>();
		}
		this.assetParts.add(assetPartsItem);
		return this;
	}

	/**
	 * Get assetParts
	 *
	 * @return assetParts
	 **/
	@ApiModelProperty(value = "")
	public List<OefAssetPart> getAssetParts() {
		return assetParts;
	}

	public void setAssetParts(List<OefAssetPart> assetParts) {
		this.assetParts = assetParts;
	}

	public BrokerOefInvestmentProgram id(UUID id) {
		this.id = id;
		return this;
	}

	/**
	 * Get id
	 *
	 * @return id
	 **/
	@ApiModelProperty(value = "")
	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public BrokerOefInvestmentProgram managerAccountId(UUID managerAccountId) {
		this.managerAccountId = managerAccountId;
		return this;
	}

	/**
	 * Get managerAccountId
	 *
	 * @return managerAccountId
	 **/
	@ApiModelProperty(value = "")
	public UUID getManagerAccountId() {
		return managerAccountId;
	}

	public void setManagerAccountId(UUID managerAccountId) {
		this.managerAccountId = managerAccountId;
	}

	public BrokerOefInvestmentProgram dateFrom(DateTime dateFrom) {
		this.dateFrom = dateFrom;
		return this;
	}

	/**
	 * Get dateFrom
	 *
	 * @return dateFrom
	 **/
	@ApiModelProperty(value = "")
	public DateTime getDateFrom() {
		return dateFrom;
	}

	public void setDateFrom(DateTime dateFrom) {
		this.dateFrom = dateFrom;
	}

	public BrokerOefInvestmentProgram dateTo(DateTime dateTo) {
		this.dateTo = dateTo;
		return this;
	}

	/**
	 * Get dateTo
	 *
	 * @return dateTo
	 **/
	@ApiModelProperty(value = "")
	public DateTime getDateTo() {
		return dateTo;
	}

	public void setDateTo(DateTime dateTo) {
		this.dateTo = dateTo;
	}

	public BrokerOefInvestmentProgram description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * Get description
	 *
	 * @return description
	 **/
	@ApiModelProperty(value = "")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BrokerOefInvestmentProgram isEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
		return this;
	}

	/**
	 * Get isEnabled
	 *
	 * @return isEnabled
	 **/
	@ApiModelProperty(value = "")
	public Boolean isIsEnabled() {
		return isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	public BrokerOefInvestmentProgram investMinAmount(Double investMinAmount) {
		this.investMinAmount = investMinAmount;
		return this;
	}

	/**
	 * Get investMinAmount
	 *
	 * @return investMinAmount
	 **/
	@ApiModelProperty(value = "")
	public Double getInvestMinAmount() {
		return investMinAmount;
	}

	public void setInvestMinAmount(Double investMinAmount) {
		this.investMinAmount = investMinAmount;
	}

	public BrokerOefInvestmentProgram investMaxAmount(Double investMaxAmount) {
		this.investMaxAmount = investMaxAmount;
		return this;
	}

	/**
	 * Get investMaxAmount
	 *
	 * @return investMaxAmount
	 **/
	@ApiModelProperty(value = "")
	public Double getInvestMaxAmount() {
		return investMaxAmount;
	}

	public void setInvestMaxAmount(Double investMaxAmount) {
		this.investMaxAmount = investMaxAmount;
	}

	public BrokerOefInvestmentProgram ipfsHash(String ipfsHash) {
		this.ipfsHash = ipfsHash;
		return this;
	}

	/**
	 * Get ipfsHash
	 *
	 * @return ipfsHash
	 **/
	@ApiModelProperty(value = "")
	public String getIpfsHash() {
		return ipfsHash;
	}

	public void setIpfsHash(String ipfsHash) {
		this.ipfsHash = ipfsHash;
	}

	public BrokerOefInvestmentProgram balance(Double balance) {
		this.balance = balance;
		return this;
	}

	/**
	 * Get balance
	 *
	 * @return balance
	 **/
	@ApiModelProperty(value = "")
	public Double getBalance() {
		return balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BrokerOefInvestmentProgram brokerOefInvestmentProgram = (BrokerOefInvestmentProgram) o;
		return Objects.equals(this.feeEntrance, brokerOefInvestmentProgram.feeEntrance) &&
				Objects.equals(this.feeExit, brokerOefInvestmentProgram.feeExit) &&
				Objects.equals(this.feeManagement, brokerOefInvestmentProgram.feeManagement) &&
				Objects.equals(this.balancingIpfsHash, brokerOefInvestmentProgram.balancingIpfsHash) &&
				Objects.equals(this.lastPeriod, brokerOefInvestmentProgram.lastPeriod) &&
				Objects.equals(this.assetParts, brokerOefInvestmentProgram.assetParts) &&
				Objects.equals(this.id, brokerOefInvestmentProgram.id) &&
				Objects.equals(this.managerAccountId, brokerOefInvestmentProgram.managerAccountId) &&
				Objects.equals(this.dateFrom, brokerOefInvestmentProgram.dateFrom) &&
				Objects.equals(this.dateTo, brokerOefInvestmentProgram.dateTo) &&
				Objects.equals(this.description, brokerOefInvestmentProgram.description) &&
				Objects.equals(this.isEnabled, brokerOefInvestmentProgram.isEnabled) &&
				Objects.equals(this.investMinAmount, brokerOefInvestmentProgram.investMinAmount) &&
				Objects.equals(this.investMaxAmount, brokerOefInvestmentProgram.investMaxAmount) &&
				Objects.equals(this.ipfsHash, brokerOefInvestmentProgram.ipfsHash) &&
				Objects.equals(this.balance, brokerOefInvestmentProgram.balance);
	}

	@Override
	public int hashCode() {
		return Objects.hash(feeEntrance, feeExit, feeManagement, balancingIpfsHash, lastPeriod, assetParts, id, managerAccountId, dateFrom, dateTo, description, isEnabled, investMinAmount, investMaxAmount, ipfsHash, balance);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BrokerOefInvestmentProgram {\n");

		sb.append("    feeEntrance: ").append(toIndentedString(feeEntrance)).append("\n");
		sb.append("    feeExit: ").append(toIndentedString(feeExit)).append("\n");
		sb.append("    feeManagement: ").append(toIndentedString(feeManagement)).append("\n");
		sb.append("    balancingIpfsHash: ").append(toIndentedString(balancingIpfsHash)).append("\n");
		sb.append("    lastPeriod: ").append(toIndentedString(lastPeriod)).append("\n");
		sb.append("    assetParts: ").append(toIndentedString(assetParts)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    managerAccountId: ").append(toIndentedString(managerAccountId)).append("\n");
		sb.append("    dateFrom: ").append(toIndentedString(dateFrom)).append("\n");
		sb.append("    dateTo: ").append(toIndentedString(dateTo)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
		sb.append("    investMinAmount: ").append(toIndentedString(investMinAmount)).append("\n");
		sb.append("    investMaxAmount: ").append(toIndentedString(investMaxAmount)).append("\n");
		sb.append("    ipfsHash: ").append(toIndentedString(ipfsHash)).append("\n");
		sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

