/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * BrokerDetails
 */

public class BrokerDetails
{
	@SerializedName("isForex")
	private Boolean isForex = null;

	@SerializedName("logo")
	private String logo = null;

	@SerializedName("showSwaps")
	private Boolean showSwaps = null;

	@SerializedName("showTickets")
	private Boolean showTickets = null;

	@SerializedName("name")
	private String name = null;

	public BrokerDetails isForex(Boolean isForex) {
		this.isForex = isForex;
		return this;
	}

	/**
	 * Get isForex
	 *
	 * @return isForex
	 **/
	@ApiModelProperty(value = "")
	public Boolean isIsForex() {
		return isForex;
	}

	public void setIsForex(Boolean isForex) {
		this.isForex = isForex;
	}

	public BrokerDetails logo(String logo) {
		this.logo = logo;
		return this;
	}

	/**
	 * Get logo
	 *
	 * @return logo
	 **/
	@ApiModelProperty(value = "")
	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public BrokerDetails showSwaps(Boolean showSwaps) {
		this.showSwaps = showSwaps;
		return this;
	}

	/**
	 * Get showSwaps
	 *
	 * @return showSwaps
	 **/
	@ApiModelProperty(value = "")
	public Boolean isShowSwaps() {
		return showSwaps;
	}

	public void setShowSwaps(Boolean showSwaps) {
		this.showSwaps = showSwaps;
	}

	public BrokerDetails showTickets(Boolean showTickets) {
		this.showTickets = showTickets;
		return this;
	}

	/**
	 * Get showTickets
	 *
	 * @return showTickets
	 **/
	@ApiModelProperty(value = "")
	public Boolean isShowTickets() {
		return showTickets;
	}

	public void setShowTickets(Boolean showTickets) {
		this.showTickets = showTickets;
	}

	public BrokerDetails name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Get name
	 *
	 * @return name
	 **/
	@ApiModelProperty(value = "")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BrokerDetails brokerDetails = (BrokerDetails) o;
		return Objects.equals(this.isForex, brokerDetails.isForex) &&
				Objects.equals(this.logo, brokerDetails.logo) &&
				Objects.equals(this.showSwaps, brokerDetails.showSwaps) &&
				Objects.equals(this.showTickets, brokerDetails.showTickets) &&
				Objects.equals(this.name, brokerDetails.name);
	}

	@Override
	public int hashCode() {
		return Objects.hash(isForex, logo, showSwaps, showTickets, name);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BrokerDetails {\n");

		sb.append("    isForex: ").append(toIndentedString(isForex)).append("\n");
		sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
		sb.append("    showSwaps: ").append(toIndentedString(showSwaps)).append("\n");
		sb.append("    showTickets: ").append(toIndentedString(showTickets)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

