/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CommonPublicAssetsViewModel
 */


public class CommonPublicAssetsViewModel implements Parcelable
{
	public static final Parcelable.Creator<CommonPublicAssetsViewModel> CREATOR = new Parcelable.Creator<CommonPublicAssetsViewModel>()
	{
		public CommonPublicAssetsViewModel createFromParcel(Parcel in) {
			return new CommonPublicAssetsViewModel(in);
		}

		public CommonPublicAssetsViewModel[] newArray(int size) {
			return new CommonPublicAssetsViewModel[size];
		}
	};

	@SerializedName("programs")
	private ItemsViewModelProgramDetailsListItem programs = null;

	@SerializedName("funds")
	private ItemsViewModelFundDetailsListItem funds = null;

	@SerializedName("follows")
	private ItemsViewModelFollowDetailsListItem follows = null;

	@SerializedName("managers")
	private ItemsViewModelPublicProfile managers = null;

	public CommonPublicAssetsViewModel() {
	}

	CommonPublicAssetsViewModel(Parcel in) {
		programs = (ItemsViewModelProgramDetailsListItem) in.readValue(ItemsViewModelProgramDetailsListItem.class.getClassLoader());
		funds = (ItemsViewModelFundDetailsListItem) in.readValue(ItemsViewModelFundDetailsListItem.class.getClassLoader());
		follows = (ItemsViewModelFollowDetailsListItem) in.readValue(ItemsViewModelFollowDetailsListItem.class.getClassLoader());
		managers = (ItemsViewModelPublicProfile) in.readValue(ItemsViewModelPublicProfile.class.getClassLoader());
	}

	public CommonPublicAssetsViewModel programs(ItemsViewModelProgramDetailsListItem programs) {
		this.programs = programs;
		return this;
	}

	/**
	 * Get programs
	 *
	 * @return programs
	 **/
	@Schema(description = "")
	public ItemsViewModelProgramDetailsListItem getPrograms() {
		return programs;
	}

	public void setPrograms(ItemsViewModelProgramDetailsListItem programs) {
		this.programs = programs;
	}

	public CommonPublicAssetsViewModel funds(ItemsViewModelFundDetailsListItem funds) {
		this.funds = funds;
		return this;
	}

	/**
	 * Get funds
	 *
	 * @return funds
	 **/
	@Schema(description = "")
	public ItemsViewModelFundDetailsListItem getFunds() {
		return funds;
	}

	public void setFunds(ItemsViewModelFundDetailsListItem funds) {
		this.funds = funds;
	}

	public CommonPublicAssetsViewModel follows(ItemsViewModelFollowDetailsListItem follows) {
		this.follows = follows;
		return this;
	}

	/**
	 * Get follows
	 *
	 * @return follows
	 **/
	@Schema(description = "")
	public ItemsViewModelFollowDetailsListItem getFollows() {
		return follows;
	}

	public void setFollows(ItemsViewModelFollowDetailsListItem follows) {
		this.follows = follows;
	}

	public CommonPublicAssetsViewModel managers(ItemsViewModelPublicProfile managers) {
		this.managers = managers;
		return this;
	}

	/**
	 * Get managers
	 *
	 * @return managers
	 **/
	@Schema(description = "")
	public ItemsViewModelPublicProfile getManagers() {
		return managers;
	}

	public void setManagers(ItemsViewModelPublicProfile managers) {
		this.managers = managers;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CommonPublicAssetsViewModel commonPublicAssetsViewModel = (CommonPublicAssetsViewModel) o;
		return Objects.equals(this.programs, commonPublicAssetsViewModel.programs) &&
				Objects.equals(this.funds, commonPublicAssetsViewModel.funds) &&
				Objects.equals(this.follows, commonPublicAssetsViewModel.follows) &&
				Objects.equals(this.managers, commonPublicAssetsViewModel.managers);
	}

	@Override
	public int hashCode() {
		return Objects.hash(programs, funds, follows, managers);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CommonPublicAssetsViewModel {\n");

		sb.append("    programs: ").append(toIndentedString(programs)).append("\n");
		sb.append("    funds: ").append(toIndentedString(funds)).append("\n");
		sb.append("    follows: ").append(toIndentedString(follows)).append("\n");
		sb.append("    managers: ").append(toIndentedString(managers)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public void writeToParcel(Parcel out, int flags) {
		out.writeValue(programs);
		out.writeValue(funds);
		out.writeValue(follows);
		out.writeValue(managers);
	}

	public int describeContents() {
		return 0;
	}
}
