/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * EventTradingItemFilters
 */


public class EventTradingItemFilters implements Parcelable
{
	public static final Parcelable.Creator<EventTradingItemFilters> CREATOR = new Parcelable.Creator<EventTradingItemFilters>()
	{
		public EventTradingItemFilters createFromParcel(Parcel in) {
			return new EventTradingItemFilters(in);
		}

		public EventTradingItemFilters[] newArray(int size) {
			return new EventTradingItemFilters[size];
		}
	};

	@SerializedName("signalProgramDetails")
	private List<FilterItemInfo> signalProgramDetails = null;

	@SerializedName("allAssets")
	private List<FilterItemInfo> allAssets = null;

	@SerializedName("programDetails")
	private List<FilterItemInfo> programDetails = null;

	@SerializedName("fundDetails")
	private List<FilterItemInfo> fundDetails = null;

	public EventTradingItemFilters() {
	}

	EventTradingItemFilters(Parcel in) {
		signalProgramDetails = (List<FilterItemInfo>) in.readValue(FilterItemInfo.class.getClassLoader());
		allAssets = (List<FilterItemInfo>) in.readValue(FilterItemInfo.class.getClassLoader());
		programDetails = (List<FilterItemInfo>) in.readValue(FilterItemInfo.class.getClassLoader());
		fundDetails = (List<FilterItemInfo>) in.readValue(FilterItemInfo.class.getClassLoader());
	}

	public EventTradingItemFilters signalProgramDetails(List<FilterItemInfo> signalProgramDetails) {
		this.signalProgramDetails = signalProgramDetails;
		return this;
	}

	public EventTradingItemFilters addSignalProgramDetailsItem(FilterItemInfo signalProgramDetailsItem) {
		if (this.signalProgramDetails == null) {
			this.signalProgramDetails = new ArrayList<FilterItemInfo>();
		}
		this.signalProgramDetails.add(signalProgramDetailsItem);
		return this;
	}

	/**
	 * Get signalProgramDetails
	 *
	 * @return signalProgramDetails
	 **/
	@Schema(description = "")
	public List<FilterItemInfo> getSignalProgramDetails() {
		return signalProgramDetails;
	}

	public void setSignalProgramDetails(List<FilterItemInfo> signalProgramDetails) {
		this.signalProgramDetails = signalProgramDetails;
	}

	public EventTradingItemFilters allAssets(List<FilterItemInfo> allAssets) {
		this.allAssets = allAssets;
		return this;
	}

	public EventTradingItemFilters addAllAssetsItem(FilterItemInfo allAssetsItem) {
		if (this.allAssets == null) {
			this.allAssets = new ArrayList<FilterItemInfo>();
		}
		this.allAssets.add(allAssetsItem);
		return this;
	}

	/**
	 * Get allAssets
	 *
	 * @return allAssets
	 **/
	@Schema(description = "")
	public List<FilterItemInfo> getAllAssets() {
		return allAssets;
	}

	public void setAllAssets(List<FilterItemInfo> allAssets) {
		this.allAssets = allAssets;
	}

	public EventTradingItemFilters programDetails(List<FilterItemInfo> programDetails) {
		this.programDetails = programDetails;
		return this;
	}

	public EventTradingItemFilters addProgramDetailsItem(FilterItemInfo programDetailsItem) {
		if (this.programDetails == null) {
			this.programDetails = new ArrayList<FilterItemInfo>();
		}
		this.programDetails.add(programDetailsItem);
		return this;
	}

	/**
	 * Get programDetails
	 *
	 * @return programDetails
	 **/
	@Schema(description = "")
	public List<FilterItemInfo> getProgramDetails() {
		return programDetails;
	}

	public void setProgramDetails(List<FilterItemInfo> programDetails) {
		this.programDetails = programDetails;
	}

	public EventTradingItemFilters fundDetails(List<FilterItemInfo> fundDetails) {
		this.fundDetails = fundDetails;
		return this;
	}

	public EventTradingItemFilters addFundDetailsItem(FilterItemInfo fundDetailsItem) {
		if (this.fundDetails == null) {
			this.fundDetails = new ArrayList<FilterItemInfo>();
		}
		this.fundDetails.add(fundDetailsItem);
		return this;
	}

	/**
	 * Get fundDetails
	 *
	 * @return fundDetails
	 **/
	@Schema(description = "")
	public List<FilterItemInfo> getFundDetails() {
		return fundDetails;
	}

	public void setFundDetails(List<FilterItemInfo> fundDetails) {
		this.fundDetails = fundDetails;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EventTradingItemFilters eventTradingItemFilters = (EventTradingItemFilters) o;
		return Objects.equals(this.signalProgramDetails, eventTradingItemFilters.signalProgramDetails) &&
				Objects.equals(this.allAssets, eventTradingItemFilters.allAssets) &&
				Objects.equals(this.programDetails, eventTradingItemFilters.programDetails) &&
				Objects.equals(this.fundDetails, eventTradingItemFilters.fundDetails);
	}

	@Override
	public int hashCode() {
		return Objects.hash(signalProgramDetails, allAssets, programDetails, fundDetails);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EventTradingItemFilters {\n");

		sb.append("    signalProgramDetails: ").append(toIndentedString(signalProgramDetails)).append("\n");
		sb.append("    allAssets: ").append(toIndentedString(allAssets)).append("\n");
		sb.append("    programDetails: ").append(toIndentedString(programDetails)).append("\n");
		sb.append("    fundDetails: ").append(toIndentedString(fundDetails)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public void writeToParcel(Parcel out, int flags) {
		out.writeValue(signalProgramDetails);
		out.writeValue(allAssets);
		out.writeValue(programDetails);
		out.writeValue(fundDetails);
	}

	public int describeContents() {
		return 0;
	}
}
