/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * EventFilters
 */


public class EventFilters implements Parcelable
{
	public static final Parcelable.Creator<EventFilters> CREATOR = new Parcelable.Creator<EventFilters>()
	{
		public EventFilters createFromParcel(Parcel in) {
			return new EventFilters(in);
		}

		public EventFilters[] newArray(int size) {
			return new EventFilters[size];
		}
	};

	@SerializedName("investingHistory")
	private EventInvestingItemFilters investingHistory = null;

	@SerializedName("tradingHistory")
	private EventTradingItemFilters tradingHistory = null;

	public EventFilters() {
	}

	EventFilters(Parcel in) {
		investingHistory = (EventInvestingItemFilters) in.readValue(EventInvestingItemFilters.class.getClassLoader());
		tradingHistory = (EventTradingItemFilters) in.readValue(EventTradingItemFilters.class.getClassLoader());
	}

	public EventFilters investingHistory(EventInvestingItemFilters investingHistory) {
		this.investingHistory = investingHistory;
		return this;
	}

	/**
	 * Get investingHistory
	 *
	 * @return investingHistory
	 **/
	@Schema(description = "")
	public EventInvestingItemFilters getInvestingHistory() {
		return investingHistory;
	}

	public void setInvestingHistory(EventInvestingItemFilters investingHistory) {
		this.investingHistory = investingHistory;
	}

	public EventFilters tradingHistory(EventTradingItemFilters tradingHistory) {
		this.tradingHistory = tradingHistory;
		return this;
	}

	/**
	 * Get tradingHistory
	 *
	 * @return tradingHistory
	 **/
	@Schema(description = "")
	public EventTradingItemFilters getTradingHistory() {
		return tradingHistory;
	}

	public void setTradingHistory(EventTradingItemFilters tradingHistory) {
		this.tradingHistory = tradingHistory;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EventFilters eventFilters = (EventFilters) o;
		return Objects.equals(this.investingHistory, eventFilters.investingHistory) &&
				Objects.equals(this.tradingHistory, eventFilters.tradingHistory);
	}

	@Override
	public int hashCode() {
		return Objects.hash(investingHistory, tradingHistory);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EventFilters {\n");

		sb.append("    investingHistory: ").append(toIndentedString(investingHistory)).append("\n");
		sb.append("    tradingHistory: ").append(toIndentedString(tradingHistory)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public void writeToParcel(Parcel out, int flags) {
		out.writeValue(investingHistory);
		out.writeValue(tradingHistory);
	}

	public int describeContents() {
		return 0;
	}
}
