/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import android.os.Parcelable;
import android.os.Parcel;
/**
 * ExchangeCredentials
 */


public class ExchangeCredentials implements Parcelable {
  @SerializedName("apiKey")
  private String apiKey = null;

  @SerializedName("apiSecret")
  private String apiSecret = null;

  public ExchangeCredentials() {
  }
  public ExchangeCredentials apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @Schema(description = "")
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public ExchangeCredentials apiSecret(String apiSecret) {
    this.apiSecret = apiSecret;
    return this;
  }

   /**
   * Get apiSecret
   * @return apiSecret
  **/
  @Schema(description = "")
  public String getApiSecret() {
    return apiSecret;
  }

  public void setApiSecret(String apiSecret) {
    this.apiSecret = apiSecret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExchangeCredentials exchangeCredentials = (ExchangeCredentials) o;
    return Objects.equals(this.apiKey, exchangeCredentials.apiKey) &&
        Objects.equals(this.apiSecret, exchangeCredentials.apiSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, apiSecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExchangeCredentials {\n");
    
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    apiSecret: ").append(toIndentedString(apiSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(apiKey);
    out.writeValue(apiSecret);
  }

  ExchangeCredentials(Parcel in) {
    apiKey = (String)in.readValue(null);
    apiSecret = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<ExchangeCredentials> CREATOR = new Parcelable.Creator<ExchangeCredentials>() {
    public ExchangeCredentials createFromParcel(Parcel in) {
      return new ExchangeCredentials(in);
    }
    public ExchangeCredentials[] newArray(int size) {
      return new ExchangeCredentials[size];
    }
  };
}
