/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * FundBalanceChart
 */

public class FundBalanceChart
{
	@SerializedName("usdBalance")
	private Double usdBalance = null;

	@SerializedName("balanceChart")
	private List<BalanceChartElement> balanceChart = null;

	@SerializedName("gvtBalance")
	private Double gvtBalance = null;

	public FundBalanceChart usdBalance(Double usdBalance) {
		this.usdBalance = usdBalance;
		return this;
	}

	/**
	 * Get usdBalance
	 *
	 * @return usdBalance
	 **/
	@ApiModelProperty(value = "")
	public Double getUsdBalance() {
		return usdBalance;
	}

	public void setUsdBalance(Double usdBalance) {
		this.usdBalance = usdBalance;
	}

	public FundBalanceChart balanceChart(List<BalanceChartElement> balanceChart) {
		this.balanceChart = balanceChart;
		return this;
	}

	public FundBalanceChart addBalanceChartItem(BalanceChartElement balanceChartItem) {
		if (this.balanceChart == null) {
			this.balanceChart = new ArrayList<BalanceChartElement>();
		}
		this.balanceChart.add(balanceChartItem);
		return this;
	}

	/**
	 * Get balanceChart
	 *
	 * @return balanceChart
	 **/
	@ApiModelProperty(value = "")
	public List<BalanceChartElement> getBalanceChart() {
		return balanceChart;
	}

	public void setBalanceChart(List<BalanceChartElement> balanceChart) {
		this.balanceChart = balanceChart;
	}

	public FundBalanceChart gvtBalance(Double gvtBalance) {
		this.gvtBalance = gvtBalance;
		return this;
	}

	/**
	 * Get gvtBalance
	 *
	 * @return gvtBalance
	 **/
	@ApiModelProperty(value = "")
	public Double getGvtBalance() {
		return gvtBalance;
	}

	public void setGvtBalance(Double gvtBalance) {
		this.gvtBalance = gvtBalance;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FundBalanceChart fundBalanceChart = (FundBalanceChart) o;
		return Objects.equals(this.usdBalance, fundBalanceChart.usdBalance) &&
				Objects.equals(this.balanceChart, fundBalanceChart.balanceChart) &&
				Objects.equals(this.gvtBalance, fundBalanceChart.gvtBalance);
	}

	@Override
	public int hashCode() {
		return Objects.hash(usdBalance, balanceChart, gvtBalance);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FundBalanceChart {\n");

		sb.append("    usdBalance: ").append(toIndentedString(usdBalance)).append("\n");
		sb.append("    balanceChart: ").append(toIndentedString(balanceChart)).append("\n");
		sb.append("    gvtBalance: ").append(toIndentedString(gvtBalance)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

