/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * FundAssetsListInfo
 */

public class FundAssetsListInfo
{
	@SerializedName("assets")
	private List<FundAssetInfo> assets = null;

	public FundAssetsListInfo assets(List<FundAssetInfo> assets) {
		this.assets = assets;
		return this;
	}

	public FundAssetsListInfo addAssetsItem(FundAssetInfo assetsItem) {
		if (this.assets == null) {
			this.assets = new ArrayList<FundAssetInfo>();
		}
		this.assets.add(assetsItem);
		return this;
	}

	/**
	 * Get assets
	 *
	 * @return assets
	 **/
	@ApiModelProperty(value = "")
	public List<FundAssetInfo> getAssets() {
		return assets;
	}

	public void setAssets(List<FundAssetInfo> assets) {
		this.assets = assets;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FundAssetsListInfo fundAssetsListInfo = (FundAssetsListInfo) o;
		return Objects.equals(this.assets, fundAssetsListInfo.assets);
	}

	@Override
	public int hashCode() {
		return Objects.hash(assets);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FundAssetsListInfo {\n");

		sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

