/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * FundAssetPartDetails
 */

public class FundAssetPartDetails
{
	@SerializedName("name")
	private String name = null;

	@SerializedName("symbol")
	private String symbol = null;

	@SerializedName("assetPart")
	private Double assetPart = null;

	public FundAssetPartDetails name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Get name
	 *
	 * @return name
	 **/
	@ApiModelProperty(value = "")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public FundAssetPartDetails symbol(String symbol) {
		this.symbol = symbol;
		return this;
	}

	/**
	 * Get symbol
	 *
	 * @return symbol
	 **/
	@ApiModelProperty(value = "")
	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public FundAssetPartDetails assetPart(Double assetPart) {
		this.assetPart = assetPart;
		return this;
	}

	/**
	 * Get assetPart
	 *
	 * @return assetPart
	 **/
	@ApiModelProperty(value = "")
	public Double getAssetPart() {
		return assetPart;
	}

	public void setAssetPart(Double assetPart) {
		this.assetPart = assetPart;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FundAssetPartDetails fundAssetPartDetails = (FundAssetPartDetails) o;
		return Objects.equals(this.name, fundAssetPartDetails.name) &&
				Objects.equals(this.symbol, fundAssetPartDetails.symbol) &&
				Objects.equals(this.assetPart, fundAssetPartDetails.assetPart);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, symbol, assetPart);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FundAssetPartDetails {\n");

		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
		sb.append("    assetPart: ").append(toIndentedString(assetPart)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

