/*
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;
import java.util.UUID;

import io.swagger.annotations.ApiModelProperty;

/**
 * InvestmentShort
 */

public class InvestmentShort
{
	@SerializedName("id")
	private UUID id = null;

	@SerializedName("managerAccountId")
	private UUID managerAccountId = null;

	@SerializedName("managerTokensId")
	private UUID managerTokensId = null;

	@SerializedName("logo")
	private String logo = null;

	@SerializedName("description")
	private String description = null;

	@SerializedName("isEnabled")
	private Boolean isEnabled = null;

	@SerializedName("rating")
	private Double rating = null;

	@SerializedName("ordersCount")
	private Integer ordersCount = null;

	@SerializedName("totalProfit")
	private Double totalProfit = null;

	public InvestmentShort id(UUID id) {
		this.id = id;
		return this;
	}

	/**
	 * Get id
	 *
	 * @return id
	 **/
	@ApiModelProperty(value = "")
	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public InvestmentShort managerAccountId(UUID managerAccountId) {
		this.managerAccountId = managerAccountId;
		return this;
	}

	/**
	 * Get managerAccountId
	 *
	 * @return managerAccountId
	 **/
	@ApiModelProperty(value = "")
	public UUID getManagerAccountId() {
		return managerAccountId;
	}

	public void setManagerAccountId(UUID managerAccountId) {
		this.managerAccountId = managerAccountId;
	}

	public InvestmentShort managerTokensId(UUID managerTokensId) {
		this.managerTokensId = managerTokensId;
		return this;
	}

	/**
	 * Get managerTokensId
	 *
	 * @return managerTokensId
	 **/
	@ApiModelProperty(value = "")
	public UUID getManagerTokensId() {
		return managerTokensId;
	}

	public void setManagerTokensId(UUID managerTokensId) {
		this.managerTokensId = managerTokensId;
	}

	public InvestmentShort logo(String logo) {
		this.logo = logo;
		return this;
	}

	/**
	 * Get logo
	 *
	 * @return logo
	 **/
	@ApiModelProperty(value = "")
	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public InvestmentShort description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * Get description
	 *
	 * @return description
	 **/
	@ApiModelProperty(value = "")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public InvestmentShort isEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
		return this;
	}

	/**
	 * Get isEnabled
	 *
	 * @return isEnabled
	 **/
	@ApiModelProperty(value = "")
	public Boolean isIsEnabled() {
		return isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	public InvestmentShort rating(Double rating) {
		this.rating = rating;
		return this;
	}

	/**
	 * Get rating
	 *
	 * @return rating
	 **/
	@ApiModelProperty(value = "")
	public Double getRating() {
		return rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	public InvestmentShort ordersCount(Integer ordersCount) {
		this.ordersCount = ordersCount;
		return this;
	}

	/**
	 * Get ordersCount
	 *
	 * @return ordersCount
	 **/
	@ApiModelProperty(value = "")
	public Integer getOrdersCount() {
		return ordersCount;
	}

	public void setOrdersCount(Integer ordersCount) {
		this.ordersCount = ordersCount;
	}

	public InvestmentShort totalProfit(Double totalProfit) {
		this.totalProfit = totalProfit;
		return this;
	}

	/**
	 * Get totalProfit
	 *
	 * @return totalProfit
	 **/
	@ApiModelProperty(value = "")
	public Double getTotalProfit() {
		return totalProfit;
	}

	public void setTotalProfit(Double totalProfit) {
		this.totalProfit = totalProfit;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		InvestmentShort investmentShort = (InvestmentShort) o;
		return Objects.equals(this.id, investmentShort.id) &&
				Objects.equals(this.managerAccountId, investmentShort.managerAccountId) &&
				Objects.equals(this.managerTokensId, investmentShort.managerTokensId) &&
				Objects.equals(this.logo, investmentShort.logo) &&
				Objects.equals(this.description, investmentShort.description) &&
				Objects.equals(this.isEnabled, investmentShort.isEnabled) &&
				Objects.equals(this.rating, investmentShort.rating) &&
				Objects.equals(this.ordersCount, investmentShort.ordersCount) &&
				Objects.equals(this.totalProfit, investmentShort.totalProfit);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, managerAccountId, managerTokensId, logo, description, isEnabled, rating, ordersCount, totalProfit);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class InvestmentShort {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    managerAccountId: ").append(toIndentedString(managerAccountId)).append("\n");
		sb.append("    managerTokensId: ").append(toIndentedString(managerTokensId)).append("\n");
		sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
		sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
		sb.append("    ordersCount: ").append(toIndentedString(ordersCount)).append("\n");
		sb.append("    totalProfit: ").append(toIndentedString(totalProfit)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

