/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * LevelsParamsInfo
 */


public class LevelsParamsInfo implements Parcelable
{
	public static final Parcelable.Creator<LevelsParamsInfo> CREATOR = new Parcelable.Creator<LevelsParamsInfo>()
	{
		public LevelsParamsInfo createFromParcel(Parcel in) {
			return new LevelsParamsInfo(in);
		}

		public LevelsParamsInfo[] newArray(int size) {
			return new LevelsParamsInfo[size];
		}
	};

	@SerializedName("minAvailableToInvest")
	private Double minAvailableToInvest = null;

	@SerializedName("maxAvailableToInvest")
	private Double maxAvailableToInvest = null;

	@SerializedName("unverifiedAvailableToInvest")
	private Double unverifiedAvailableToInvest = null;

	@SerializedName("genesisRatioMin")
	private Double genesisRatioMin = null;

	@SerializedName("genesisRatioMax")
	private Double genesisRatioMax = null;

	@SerializedName("genesisRatioHighRisk")
	private Double genesisRatioHighRisk = null;

	@SerializedName("volumeScaleMin")
	private Double volumeScaleMin = null;

	@SerializedName("volumeScaleMax")
	private Double volumeScaleMax = null;

	@SerializedName("programAgeMax")
	private Double programAgeMax = null;

	@SerializedName("ageByVolumeMax")
	private Double ageByVolumeMax = null;

	@SerializedName("investmentScaleMin")
	private Double investmentScaleMin = null;

	@SerializedName("investmentScaleMax")
	private Double investmentScaleMax = null;

	@SerializedName("investmentScaleHighRisk")
	private Double investmentScaleHighRisk = null;

	public LevelsParamsInfo() {
	}

	LevelsParamsInfo(Parcel in) {
		minAvailableToInvest = (Double) in.readValue(null);
		maxAvailableToInvest = (Double) in.readValue(null);
		unverifiedAvailableToInvest = (Double) in.readValue(null);
		genesisRatioMin = (Double) in.readValue(null);
		genesisRatioMax = (Double) in.readValue(null);
		genesisRatioHighRisk = (Double) in.readValue(null);
		volumeScaleMin = (Double) in.readValue(null);
		volumeScaleMax = (Double) in.readValue(null);
		programAgeMax = (Double) in.readValue(null);
		ageByVolumeMax = (Double) in.readValue(null);
		investmentScaleMin = (Double) in.readValue(null);
		investmentScaleMax = (Double) in.readValue(null);
		investmentScaleHighRisk = (Double) in.readValue(null);
	}

	public LevelsParamsInfo minAvailableToInvest(Double minAvailableToInvest) {
		this.minAvailableToInvest = minAvailableToInvest;
		return this;
	}

	/**
	 * Get minAvailableToInvest
	 *
	 * @return minAvailableToInvest
	 **/
	@Schema(description = "")
	public Double getMinAvailableToInvest() {
		return minAvailableToInvest;
	}

	public void setMinAvailableToInvest(Double minAvailableToInvest) {
		this.minAvailableToInvest = minAvailableToInvest;
	}

	public LevelsParamsInfo maxAvailableToInvest(Double maxAvailableToInvest) {
		this.maxAvailableToInvest = maxAvailableToInvest;
		return this;
	}

	/**
	 * Get maxAvailableToInvest
	 *
	 * @return maxAvailableToInvest
	 **/
	@Schema(description = "")
	public Double getMaxAvailableToInvest() {
		return maxAvailableToInvest;
	}

	public void setMaxAvailableToInvest(Double maxAvailableToInvest) {
		this.maxAvailableToInvest = maxAvailableToInvest;
	}

	public LevelsParamsInfo unverifiedAvailableToInvest(Double unverifiedAvailableToInvest) {
		this.unverifiedAvailableToInvest = unverifiedAvailableToInvest;
		return this;
	}

	/**
	 * Get unverifiedAvailableToInvest
	 *
	 * @return unverifiedAvailableToInvest
	 **/
	@Schema(description = "")
	public Double getUnverifiedAvailableToInvest() {
		return unverifiedAvailableToInvest;
	}

	public void setUnverifiedAvailableToInvest(Double unverifiedAvailableToInvest) {
		this.unverifiedAvailableToInvest = unverifiedAvailableToInvest;
	}

	public LevelsParamsInfo genesisRatioMin(Double genesisRatioMin) {
		this.genesisRatioMin = genesisRatioMin;
		return this;
	}

	/**
	 * Get genesisRatioMin
	 *
	 * @return genesisRatioMin
	 **/
	@Schema(description = "")
	public Double getGenesisRatioMin() {
		return genesisRatioMin;
	}

	public void setGenesisRatioMin(Double genesisRatioMin) {
		this.genesisRatioMin = genesisRatioMin;
	}

	public LevelsParamsInfo genesisRatioMax(Double genesisRatioMax) {
		this.genesisRatioMax = genesisRatioMax;
		return this;
	}

	/**
	 * Get genesisRatioMax
	 *
	 * @return genesisRatioMax
	 **/
	@Schema(description = "")
	public Double getGenesisRatioMax() {
		return genesisRatioMax;
	}

	public void setGenesisRatioMax(Double genesisRatioMax) {
		this.genesisRatioMax = genesisRatioMax;
	}

	public LevelsParamsInfo genesisRatioHighRisk(Double genesisRatioHighRisk) {
		this.genesisRatioHighRisk = genesisRatioHighRisk;
		return this;
	}

	/**
	 * Get genesisRatioHighRisk
	 *
	 * @return genesisRatioHighRisk
	 **/
	@Schema(description = "")
	public Double getGenesisRatioHighRisk() {
		return genesisRatioHighRisk;
	}

	public void setGenesisRatioHighRisk(Double genesisRatioHighRisk) {
		this.genesisRatioHighRisk = genesisRatioHighRisk;
	}

	public LevelsParamsInfo volumeScaleMin(Double volumeScaleMin) {
		this.volumeScaleMin = volumeScaleMin;
		return this;
	}

	/**
	 * Get volumeScaleMin
	 *
	 * @return volumeScaleMin
	 **/
	@Schema(description = "")
	public Double getVolumeScaleMin() {
		return volumeScaleMin;
	}

	public void setVolumeScaleMin(Double volumeScaleMin) {
		this.volumeScaleMin = volumeScaleMin;
	}

	public LevelsParamsInfo volumeScaleMax(Double volumeScaleMax) {
		this.volumeScaleMax = volumeScaleMax;
		return this;
	}

	/**
	 * Get volumeScaleMax
	 *
	 * @return volumeScaleMax
	 **/
	@Schema(description = "")
	public Double getVolumeScaleMax() {
		return volumeScaleMax;
	}

	public void setVolumeScaleMax(Double volumeScaleMax) {
		this.volumeScaleMax = volumeScaleMax;
	}

	public LevelsParamsInfo programAgeMax(Double programAgeMax) {
		this.programAgeMax = programAgeMax;
		return this;
	}

	/**
	 * Get programAgeMax
	 *
	 * @return programAgeMax
	 **/
	@Schema(description = "")
	public Double getProgramAgeMax() {
		return programAgeMax;
	}

	public void setProgramAgeMax(Double programAgeMax) {
		this.programAgeMax = programAgeMax;
	}

	public LevelsParamsInfo ageByVolumeMax(Double ageByVolumeMax) {
		this.ageByVolumeMax = ageByVolumeMax;
		return this;
	}

	/**
	 * Get ageByVolumeMax
	 *
	 * @return ageByVolumeMax
	 **/
	@Schema(description = "")
	public Double getAgeByVolumeMax() {
		return ageByVolumeMax;
	}

	public void setAgeByVolumeMax(Double ageByVolumeMax) {
		this.ageByVolumeMax = ageByVolumeMax;
	}

	public LevelsParamsInfo investmentScaleMin(Double investmentScaleMin) {
		this.investmentScaleMin = investmentScaleMin;
		return this;
	}

	/**
	 * Get investmentScaleMin
	 *
	 * @return investmentScaleMin
	 **/
	@Schema(description = "")
	public Double getInvestmentScaleMin() {
		return investmentScaleMin;
	}

	public void setInvestmentScaleMin(Double investmentScaleMin) {
		this.investmentScaleMin = investmentScaleMin;
	}

	public LevelsParamsInfo investmentScaleMax(Double investmentScaleMax) {
		this.investmentScaleMax = investmentScaleMax;
		return this;
	}

	/**
	 * Get investmentScaleMax
	 *
	 * @return investmentScaleMax
	 **/
	@Schema(description = "")
	public Double getInvestmentScaleMax() {
		return investmentScaleMax;
	}

	public void setInvestmentScaleMax(Double investmentScaleMax) {
		this.investmentScaleMax = investmentScaleMax;
	}

	public LevelsParamsInfo investmentScaleHighRisk(Double investmentScaleHighRisk) {
		this.investmentScaleHighRisk = investmentScaleHighRisk;
		return this;
	}

	/**
	 * Get investmentScaleHighRisk
	 *
	 * @return investmentScaleHighRisk
	 **/
	@Schema(description = "")
	public Double getInvestmentScaleHighRisk() {
		return investmentScaleHighRisk;
	}

	public void setInvestmentScaleHighRisk(Double investmentScaleHighRisk) {
		this.investmentScaleHighRisk = investmentScaleHighRisk;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		LevelsParamsInfo levelsParamsInfo = (LevelsParamsInfo) o;
		return Objects.equals(this.minAvailableToInvest, levelsParamsInfo.minAvailableToInvest) &&
				Objects.equals(this.maxAvailableToInvest, levelsParamsInfo.maxAvailableToInvest) &&
				Objects.equals(this.unverifiedAvailableToInvest, levelsParamsInfo.unverifiedAvailableToInvest) &&
				Objects.equals(this.genesisRatioMin, levelsParamsInfo.genesisRatioMin) &&
				Objects.equals(this.genesisRatioMax, levelsParamsInfo.genesisRatioMax) &&
				Objects.equals(this.genesisRatioHighRisk, levelsParamsInfo.genesisRatioHighRisk) &&
				Objects.equals(this.volumeScaleMin, levelsParamsInfo.volumeScaleMin) &&
				Objects.equals(this.volumeScaleMax, levelsParamsInfo.volumeScaleMax) &&
				Objects.equals(this.programAgeMax, levelsParamsInfo.programAgeMax) &&
				Objects.equals(this.ageByVolumeMax, levelsParamsInfo.ageByVolumeMax) &&
				Objects.equals(this.investmentScaleMin, levelsParamsInfo.investmentScaleMin) &&
				Objects.equals(this.investmentScaleMax, levelsParamsInfo.investmentScaleMax) &&
				Objects.equals(this.investmentScaleHighRisk, levelsParamsInfo.investmentScaleHighRisk);
	}

	@Override
	public int hashCode() {
		return Objects.hash(minAvailableToInvest, maxAvailableToInvest, unverifiedAvailableToInvest, genesisRatioMin, genesisRatioMax, genesisRatioHighRisk, volumeScaleMin, volumeScaleMax, programAgeMax, ageByVolumeMax, investmentScaleMin, investmentScaleMax, investmentScaleHighRisk);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LevelsParamsInfo {\n");

		sb.append("    minAvailableToInvest: ").append(toIndentedString(minAvailableToInvest)).append("\n");
		sb.append("    maxAvailableToInvest: ").append(toIndentedString(maxAvailableToInvest)).append("\n");
		sb.append("    unverifiedAvailableToInvest: ").append(toIndentedString(unverifiedAvailableToInvest)).append("\n");
		sb.append("    genesisRatioMin: ").append(toIndentedString(genesisRatioMin)).append("\n");
		sb.append("    genesisRatioMax: ").append(toIndentedString(genesisRatioMax)).append("\n");
		sb.append("    genesisRatioHighRisk: ").append(toIndentedString(genesisRatioHighRisk)).append("\n");
		sb.append("    volumeScaleMin: ").append(toIndentedString(volumeScaleMin)).append("\n");
		sb.append("    volumeScaleMax: ").append(toIndentedString(volumeScaleMax)).append("\n");
		sb.append("    programAgeMax: ").append(toIndentedString(programAgeMax)).append("\n");
		sb.append("    ageByVolumeMax: ").append(toIndentedString(ageByVolumeMax)).append("\n");
		sb.append("    investmentScaleMin: ").append(toIndentedString(investmentScaleMin)).append("\n");
		sb.append("    investmentScaleMax: ").append(toIndentedString(investmentScaleMax)).append("\n");
		sb.append("    investmentScaleHighRisk: ").append(toIndentedString(investmentScaleHighRisk)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public void writeToParcel(Parcel out, int flags) {
		out.writeValue(minAvailableToInvest);
		out.writeValue(maxAvailableToInvest);
		out.writeValue(unverifiedAvailableToInvest);
		out.writeValue(genesisRatioMin);
		out.writeValue(genesisRatioMax);
		out.writeValue(genesisRatioHighRisk);
		out.writeValue(volumeScaleMin);
		out.writeValue(volumeScaleMax);
		out.writeValue(programAgeMax);
		out.writeValue(ageByVolumeMax);
		out.writeValue(investmentScaleMin);
		out.writeValue(investmentScaleMax);
		out.writeValue(investmentScaleHighRisk);
	}

	public int describeContents() {
		return 0;
	}
}
