/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;
import java.util.UUID;

import io.swagger.annotations.ApiModelProperty;

/**
 * NewExternalSignalAccountRequest
 */

public class NewExternalSignalAccountRequest
{
	@SerializedName("externalKeyId")
	private UUID externalKeyId = null;

	@SerializedName("volumeFee")
	private Double volumeFee = null;

	@SerializedName("monthlySubscriptionFee")
	private Double monthlySubscriptionFee = null;

	@SerializedName("title")
	private String title = null;

	@SerializedName("description")
	private String description = null;

	@SerializedName("logo")
	private String logo = null;

	public NewExternalSignalAccountRequest externalKeyId(UUID externalKeyId) {
		this.externalKeyId = externalKeyId;
		return this;
	}

	/**
	 * Get externalKeyId
	 *
	 * @return externalKeyId
	 **/
	@ApiModelProperty(value = "")
	public UUID getExternalKeyId() {
		return externalKeyId;
	}

	public void setExternalKeyId(UUID externalKeyId) {
		this.externalKeyId = externalKeyId;
	}

	public NewExternalSignalAccountRequest volumeFee(Double volumeFee) {
		this.volumeFee = volumeFee;
		return this;
	}

	/**
	 * Get volumeFee
	 *
	 * @return volumeFee
	 **/
	@ApiModelProperty(value = "")
	public Double getVolumeFee() {
		return volumeFee;
	}

	public void setVolumeFee(Double volumeFee) {
		this.volumeFee = volumeFee;
	}

	public NewExternalSignalAccountRequest monthlySubscriptionFee(Double monthlySubscriptionFee) {
		this.monthlySubscriptionFee = monthlySubscriptionFee;
		return this;
	}

	/**
	 * Get monthlySubscriptionFee
	 *
	 * @return monthlySubscriptionFee
	 **/
	@ApiModelProperty(value = "")
	public Double getMonthlySubscriptionFee() {
		return monthlySubscriptionFee;
	}

	public void setMonthlySubscriptionFee(Double monthlySubscriptionFee) {
		this.monthlySubscriptionFee = monthlySubscriptionFee;
	}

	public NewExternalSignalAccountRequest title(String title) {
		this.title = title;
		return this;
	}

	/**
	 * Get title
	 *
	 * @return title
	 **/
	@ApiModelProperty(value = "")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public NewExternalSignalAccountRequest description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * Get description
	 *
	 * @return description
	 **/
	@ApiModelProperty(value = "")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public NewExternalSignalAccountRequest logo(String logo) {
		this.logo = logo;
		return this;
	}

	/**
	 * Get logo
	 *
	 * @return logo
	 **/
	@ApiModelProperty(value = "")
	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		NewExternalSignalAccountRequest newExternalSignalAccountRequest = (NewExternalSignalAccountRequest) o;
		return Objects.equals(this.externalKeyId, newExternalSignalAccountRequest.externalKeyId) &&
				Objects.equals(this.volumeFee, newExternalSignalAccountRequest.volumeFee) &&
				Objects.equals(this.monthlySubscriptionFee, newExternalSignalAccountRequest.monthlySubscriptionFee) &&
				Objects.equals(this.title, newExternalSignalAccountRequest.title) &&
				Objects.equals(this.description, newExternalSignalAccountRequest.description) &&
				Objects.equals(this.logo, newExternalSignalAccountRequest.logo);
	}

	@Override
	public int hashCode() {
		return Objects.hash(externalKeyId, volumeFee, monthlySubscriptionFee, title, description, logo);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class NewExternalSignalAccountRequest {\n");

		sb.append("    externalKeyId: ").append(toIndentedString(externalKeyId)).append("\n");
		sb.append("    volumeFee: ").append(toIndentedString(volumeFee)).append("\n");
		sb.append("    monthlySubscriptionFee: ").append(toIndentedString(monthlySubscriptionFee)).append("\n");
		sb.append("    title: ").append(toIndentedString(title)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

