/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.Objects;
import java.util.UUID;

import io.swagger.annotations.ApiModelProperty;

/**
 * OpenSignalTrade
 */

public class OpenSignalTrade
{
	@SerializedName("id")
	private UUID id = null;

	@SerializedName("symbol")
	private String symbol = null;

	@SerializedName("manager")
	private ProfilePublic manager = null;

	@SerializedName("orderId")
	private Integer orderId = null;

	@SerializedName("openDate")
	private DateTime openDate = null;

	@SerializedName("openPrice")
	private Double openPrice = null;

	@SerializedName("volume")
	private Double volume = null;

	@SerializedName("price")
	private Double price = null;

	@SerializedName("profit")
	private Double profit = null;

	public OpenSignalTrade id(UUID id) {
		this.id = id;
		return this;
	}

	/**
	 * Get id
	 *
	 * @return id
	 **/
	@ApiModelProperty(value = "")
	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public OpenSignalTrade symbol(String symbol) {
		this.symbol = symbol;
		return this;
	}

	/**
	 * Get symbol
	 *
	 * @return symbol
	 **/
	@ApiModelProperty(value = "")
	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public OpenSignalTrade manager(ProfilePublic manager) {
		this.manager = manager;
		return this;
	}

	/**
	 * Get manager
	 *
	 * @return manager
	 **/
	@ApiModelProperty(value = "")
	public ProfilePublic getManager() {
		return manager;
	}

	public void setManager(ProfilePublic manager) {
		this.manager = manager;
	}

	public OpenSignalTrade orderId(Integer orderId) {
		this.orderId = orderId;
		return this;
	}

	/**
	 * Get orderId
	 *
	 * @return orderId
	 **/
	@ApiModelProperty(value = "")
	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public OpenSignalTrade openDate(DateTime openDate) {
		this.openDate = openDate;
		return this;
	}

	/**
	 * Get openDate
	 *
	 * @return openDate
	 **/
	@ApiModelProperty(value = "")
	public DateTime getOpenDate() {
		return openDate;
	}

	public void setOpenDate(DateTime openDate) {
		this.openDate = openDate;
	}

	public OpenSignalTrade openPrice(Double openPrice) {
		this.openPrice = openPrice;
		return this;
	}

	/**
	 * Get openPrice
	 *
	 * @return openPrice
	 **/
	@ApiModelProperty(value = "")
	public Double getOpenPrice() {
		return openPrice;
	}

	public void setOpenPrice(Double openPrice) {
		this.openPrice = openPrice;
	}

	public OpenSignalTrade volume(Double volume) {
		this.volume = volume;
		return this;
	}

	/**
	 * Get volume
	 *
	 * @return volume
	 **/
	@ApiModelProperty(value = "")
	public Double getVolume() {
		return volume;
	}

	public void setVolume(Double volume) {
		this.volume = volume;
	}

	public OpenSignalTrade price(Double price) {
		this.price = price;
		return this;
	}

	/**
	 * Get price
	 *
	 * @return price
	 **/
	@ApiModelProperty(value = "")
	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public OpenSignalTrade profit(Double profit) {
		this.profit = profit;
		return this;
	}

	/**
	 * Get profit
	 *
	 * @return profit
	 **/
	@ApiModelProperty(value = "")
	public Double getProfit() {
		return profit;
	}

	public void setProfit(Double profit) {
		this.profit = profit;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		OpenSignalTrade openSignalTrade = (OpenSignalTrade) o;
		return Objects.equals(this.id, openSignalTrade.id) &&
				Objects.equals(this.symbol, openSignalTrade.symbol) &&
				Objects.equals(this.manager, openSignalTrade.manager) &&
				Objects.equals(this.orderId, openSignalTrade.orderId) &&
				Objects.equals(this.openDate, openSignalTrade.openDate) &&
				Objects.equals(this.openPrice, openSignalTrade.openPrice) &&
				Objects.equals(this.volume, openSignalTrade.volume) &&
				Objects.equals(this.price, openSignalTrade.price) &&
				Objects.equals(this.profit, openSignalTrade.profit);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, symbol, manager, orderId, openDate, openPrice, volume, price, profit);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class OpenSignalTrade {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
		sb.append("    manager: ").append(toIndentedString(manager)).append("\n");
		sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
		sb.append("    openDate: ").append(toIndentedString(openDate)).append("\n");
		sb.append("    openPrice: ").append(toIndentedString(openPrice)).append("\n");
		sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
		sb.append("    price: ").append(toIndentedString(price)).append("\n");
		sb.append("    profit: ").append(toIndentedString(profit)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

