/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SignalDataMaster;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import android.os.Parcelable;
import android.os.Parcel;
/**
 * OrderModelSignalData
 */


public class OrderModelSignalData implements Parcelable {
  @SerializedName("masters")
  private List<SignalDataMaster> masters = null;

  public OrderModelSignalData() {
  }
  public OrderModelSignalData masters(List<SignalDataMaster> masters) {
    this.masters = masters;
    return this;
  }

  public OrderModelSignalData addMastersItem(SignalDataMaster mastersItem) {
    if (this.masters == null) {
      this.masters = new ArrayList<SignalDataMaster>();
    }
    this.masters.add(mastersItem);
    return this;
  }

   /**
   * Get masters
   * @return masters
  **/
  @Schema(description = "")
  public List<SignalDataMaster> getMasters() {
    return masters;
  }

  public void setMasters(List<SignalDataMaster> masters) {
    this.masters = masters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderModelSignalData orderModelSignalData = (OrderModelSignalData) o;
    return Objects.equals(this.masters, orderModelSignalData.masters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(masters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderModelSignalData {\n");
    
    sb.append("    masters: ").append(toIndentedString(masters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(masters);
  }

  OrderModelSignalData(Parcel in) {
    masters = (List<SignalDataMaster>)in.readValue(SignalDataMaster.class.getClassLoader());
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<OrderModelSignalData> CREATOR = new Parcelable.Creator<OrderModelSignalData>() {
    public OrderModelSignalData createFromParcel(Parcel in) {
      return new OrderModelSignalData(in);
    }
    public OrderModelSignalData[] newArray(int size) {
      return new OrderModelSignalData[size];
    }
  };
}
