/*
 * Tournament Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * ParticipantsSummaryViewModel
 */

public class ParticipantsSummaryViewModel
{
	@SerializedName("participantsCount")
	private Integer participantsCount = null;

	@SerializedName("lastRegistrationDate")
	private DateTime lastRegistrationDate = null;

	public ParticipantsSummaryViewModel participantsCount(Integer participantsCount) {
		this.participantsCount = participantsCount;
		return this;
	}

	/**
	 * Get participantsCount
	 *
	 * @return participantsCount
	 **/
	@ApiModelProperty(value = "")
	public Integer getParticipantsCount() {
		return participantsCount;
	}

	public void setParticipantsCount(Integer participantsCount) {
		this.participantsCount = participantsCount;
	}

	public ParticipantsSummaryViewModel lastRegistrationDate(DateTime lastRegistrationDate) {
		this.lastRegistrationDate = lastRegistrationDate;
		return this;
	}

	/**
	 * Get lastRegistrationDate
	 *
	 * @return lastRegistrationDate
	 **/
	@ApiModelProperty(value = "")
	public DateTime getLastRegistrationDate() {
		return lastRegistrationDate;
	}

	public void setLastRegistrationDate(DateTime lastRegistrationDate) {
		this.lastRegistrationDate = lastRegistrationDate;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ParticipantsSummaryViewModel participantsSummaryViewModel = (ParticipantsSummaryViewModel) o;
		return Objects.equals(this.participantsCount, participantsSummaryViewModel.participantsCount) &&
				Objects.equals(this.lastRegistrationDate, participantsSummaryViewModel.lastRegistrationDate);
	}

	@Override
	public int hashCode() {
		return Objects.hash(participantsCount, lastRegistrationDate);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ParticipantsSummaryViewModel {\n");

		sb.append("    participantsCount: ").append(toIndentedString(participantsCount)).append("\n");
		sb.append("    lastRegistrationDate: ").append(toIndentedString(lastRegistrationDate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

