/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * PersonalFundDetailsFull
 */

public class PersonalFundDetailsFull
{
	@SerializedName("isFavorite")
	private Boolean isFavorite = null;

	@SerializedName("isInvested")
	private Boolean isInvested = null;

	@SerializedName("isOwnProgram")
	private Boolean isOwnProgram = null;

	@SerializedName("hasNotifications")
	private Boolean hasNotifications = null;

	@SerializedName("value")
	private Double value = null;

	@SerializedName("profit")
	private Double profit = null;

	@SerializedName("investmentProgramStatus")
	private InvestmentProgramStatusEnum investmentProgramStatus = null;

	public PersonalFundDetailsFull isFavorite(Boolean isFavorite) {
		this.isFavorite = isFavorite;
		return this;
	}

	/**
	 * Get isFavorite
	 *
	 * @return isFavorite
	 **/
	@ApiModelProperty(value = "")
	public Boolean isIsFavorite() {
		return isFavorite;
	}

	public void setIsFavorite(Boolean isFavorite) {
		this.isFavorite = isFavorite;
	}

	public PersonalFundDetailsFull isInvested(Boolean isInvested) {
		this.isInvested = isInvested;
		return this;
	}

	/**
	 * Get isInvested
	 *
	 * @return isInvested
	 **/
	@ApiModelProperty(value = "")
	public Boolean isIsInvested() {
		return isInvested;
	}

	public void setIsInvested(Boolean isInvested) {
		this.isInvested = isInvested;
	}

	public PersonalFundDetailsFull isOwnProgram(Boolean isOwnProgram) {
		this.isOwnProgram = isOwnProgram;
		return this;
	}

	/**
	 * Get isOwnProgram
	 *
	 * @return isOwnProgram
	 **/
	@ApiModelProperty(value = "")
	public Boolean isIsOwnProgram() {
		return isOwnProgram;
	}

	public void setIsOwnProgram(Boolean isOwnProgram) {
		this.isOwnProgram = isOwnProgram;
	}

	public PersonalFundDetailsFull hasNotifications(Boolean hasNotifications) {
		this.hasNotifications = hasNotifications;
		return this;
	}

	/**
	 * Get hasNotifications
	 *
	 * @return hasNotifications
	 **/
	@ApiModelProperty(value = "")
	public Boolean isHasNotifications() {
		return hasNotifications;
	}

	public void setHasNotifications(Boolean hasNotifications) {
		this.hasNotifications = hasNotifications;
	}

	public PersonalFundDetailsFull value(Double value) {
		this.value = value;
		return this;
	}

	/**
	 * Get value
	 *
	 * @return value
	 **/
	@ApiModelProperty(value = "")
	public Double getValue() {
		return value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	public PersonalFundDetailsFull profit(Double profit) {
		this.profit = profit;
		return this;
	}

	/**
	 * Get profit
	 *
	 * @return profit
	 **/
	@ApiModelProperty(value = "")
	public Double getProfit() {
		return profit;
	}

	public void setProfit(Double profit) {
		this.profit = profit;
	}

	public PersonalFundDetailsFull investmentProgramStatus(InvestmentProgramStatusEnum investmentProgramStatus) {
		this.investmentProgramStatus = investmentProgramStatus;
		return this;
	}

	/**
	 * Get investmentProgramStatus
	 *
	 * @return investmentProgramStatus
	 **/
	@ApiModelProperty(value = "")
	public InvestmentProgramStatusEnum getInvestmentProgramStatus() {
		return investmentProgramStatus;
	}

	public void setInvestmentProgramStatus(InvestmentProgramStatusEnum investmentProgramStatus) {
		this.investmentProgramStatus = investmentProgramStatus;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PersonalFundDetailsFull personalFundDetailsFull = (PersonalFundDetailsFull) o;
		return Objects.equals(this.isFavorite, personalFundDetailsFull.isFavorite) &&
				Objects.equals(this.isInvested, personalFundDetailsFull.isInvested) &&
				Objects.equals(this.isOwnProgram, personalFundDetailsFull.isOwnProgram) &&
				Objects.equals(this.hasNotifications, personalFundDetailsFull.hasNotifications) &&
				Objects.equals(this.value, personalFundDetailsFull.value) &&
				Objects.equals(this.profit, personalFundDetailsFull.profit) &&
				Objects.equals(this.investmentProgramStatus, personalFundDetailsFull.investmentProgramStatus);
	}

	@Override
	public int hashCode() {
		return Objects.hash(isFavorite, isInvested, isOwnProgram, hasNotifications, value, profit, investmentProgramStatus);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PersonalFundDetailsFull {\n");

		sb.append("    isFavorite: ").append(toIndentedString(isFavorite)).append("\n");
		sb.append("    isInvested: ").append(toIndentedString(isInvested)).append("\n");
		sb.append("    isOwnProgram: ").append(toIndentedString(isOwnProgram)).append("\n");
		sb.append("    hasNotifications: ").append(toIndentedString(hasNotifications)).append("\n");
		sb.append("    value: ").append(toIndentedString(value)).append("\n");
		sb.append("    profit: ").append(toIndentedString(profit)).append("\n");
		sb.append("    investmentProgramStatus: ").append(toIndentedString(investmentProgramStatus)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Gets or Sets investmentProgramStatus
	 */
	@JsonAdapter(InvestmentProgramStatusEnum.Adapter.class)
	public enum InvestmentProgramStatusEnum
	{
		ACTIVE("Active"),

		INVESTING("Investing"),

		WITHDRAWING("Withdrawing"),

		ENDED("Ended");

		public static InvestmentProgramStatusEnum fromValue(String text) {
			for (InvestmentProgramStatusEnum b : InvestmentProgramStatusEnum.values()) {
				if (String.valueOf(b.value).equals(text)) {
					return b;
				}
			}
			return null;
		}

		private String value;

		InvestmentProgramStatusEnum(String value) {
			this.value = value;
		}

		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		public static class Adapter extends TypeAdapter<InvestmentProgramStatusEnum>
		{
			@Override
			public void write(final JsonWriter jsonWriter, final InvestmentProgramStatusEnum enumeration) throws IOException {
				jsonWriter.value(enumeration.getValue());
			}

			@Override
			public InvestmentProgramStatusEnum read(final JsonReader jsonReader) throws IOException {
				String value = jsonReader.nextString();
				return InvestmentProgramStatusEnum.fromValue(String.valueOf(value));
			}
		}
	}

}

