/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * ProgramChart
 */

public class ProgramChart
{
	@SerializedName("chart")
	private List<ChartProgramDetails> chart = null;

	@SerializedName("pnLChart")
	private List<ChartSimple> pnLChart = null;

	@SerializedName("equity")
	private Double equity = null;

	@SerializedName("totalProfit")
	private Double totalProfit = null;

	@SerializedName("sharpeRatio")
	private Double sharpeRatio = null;

	@SerializedName("sortinoRatio")
	private Double sortinoRatio = null;

	@SerializedName("calmarRatio")
	private Double calmarRatio = null;

	@SerializedName("rate")
	private Double rate = null;

	public ProgramChart chart(List<ChartProgramDetails> chart) {
		this.chart = chart;
		return this;
	}

	public ProgramChart addChartItem(ChartProgramDetails chartItem) {
		if (this.chart == null) {
			this.chart = new ArrayList<ChartProgramDetails>();
		}
		this.chart.add(chartItem);
		return this;
	}

	/**
	 * Get chart
	 *
	 * @return chart
	 **/
	@ApiModelProperty(value = "")
	public List<ChartProgramDetails> getChart() {
		return chart;
	}

	public void setChart(List<ChartProgramDetails> chart) {
		this.chart = chart;
	}

	public ProgramChart pnLChart(List<ChartSimple> pnLChart) {
		this.pnLChart = pnLChart;
		return this;
	}

	public ProgramChart addPnLChartItem(ChartSimple pnLChartItem) {
		if (this.pnLChart == null) {
			this.pnLChart = new ArrayList<ChartSimple>();
		}
		this.pnLChart.add(pnLChartItem);
		return this;
	}

	/**
	 * Get pnLChart
	 *
	 * @return pnLChart
	 **/
	@ApiModelProperty(value = "")
	public List<ChartSimple> getPnLChart() {
		return pnLChart;
	}

	public void setPnLChart(List<ChartSimple> pnLChart) {
		this.pnLChart = pnLChart;
	}

	public ProgramChart equity(Double equity) {
		this.equity = equity;
		return this;
	}

	/**
	 * Get equity
	 *
	 * @return equity
	 **/
	@ApiModelProperty(value = "")
	public Double getEquity() {
		return equity;
	}

	public void setEquity(Double equity) {
		this.equity = equity;
	}

	public ProgramChart totalProfit(Double totalProfit) {
		this.totalProfit = totalProfit;
		return this;
	}

	/**
	 * Get totalProfit
	 *
	 * @return totalProfit
	 **/
	@ApiModelProperty(value = "")
	public Double getTotalProfit() {
		return totalProfit;
	}

	public void setTotalProfit(Double totalProfit) {
		this.totalProfit = totalProfit;
	}

	public ProgramChart sharpeRatio(Double sharpeRatio) {
		this.sharpeRatio = sharpeRatio;
		return this;
	}

	/**
	 * Get sharpeRatio
	 *
	 * @return sharpeRatio
	 **/
	@ApiModelProperty(value = "")
	public Double getSharpeRatio() {
		return sharpeRatio;
	}

	public void setSharpeRatio(Double sharpeRatio) {
		this.sharpeRatio = sharpeRatio;
	}

	public ProgramChart sortinoRatio(Double sortinoRatio) {
		this.sortinoRatio = sortinoRatio;
		return this;
	}

	/**
	 * Get sortinoRatio
	 *
	 * @return sortinoRatio
	 **/
	@ApiModelProperty(value = "")
	public Double getSortinoRatio() {
		return sortinoRatio;
	}

	public void setSortinoRatio(Double sortinoRatio) {
		this.sortinoRatio = sortinoRatio;
	}

	public ProgramChart calmarRatio(Double calmarRatio) {
		this.calmarRatio = calmarRatio;
		return this;
	}

	/**
	 * Get calmarRatio
	 *
	 * @return calmarRatio
	 **/
	@ApiModelProperty(value = "")
	public Double getCalmarRatio() {
		return calmarRatio;
	}

	public void setCalmarRatio(Double calmarRatio) {
		this.calmarRatio = calmarRatio;
	}

	public ProgramChart rate(Double rate) {
		this.rate = rate;
		return this;
	}

	/**
	 * Get rate
	 *
	 * @return rate
	 **/
	@ApiModelProperty(value = "")
	public Double getRate() {
		return rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ProgramChart programChart = (ProgramChart) o;
		return Objects.equals(this.chart, programChart.chart) &&
				Objects.equals(this.pnLChart, programChart.pnLChart) &&
				Objects.equals(this.equity, programChart.equity) &&
				Objects.equals(this.totalProfit, programChart.totalProfit) &&
				Objects.equals(this.sharpeRatio, programChart.sharpeRatio) &&
				Objects.equals(this.sortinoRatio, programChart.sortinoRatio) &&
				Objects.equals(this.calmarRatio, programChart.calmarRatio) &&
				Objects.equals(this.rate, programChart.rate);
	}

	@Override
	public int hashCode() {
		return Objects.hash(chart, pnLChart, equity, totalProfit, sharpeRatio, sortinoRatio, calmarRatio, rate);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ProgramChart {\n");

		sb.append("    chart: ").append(toIndentedString(chart)).append("\n");
		sb.append("    pnLChart: ").append(toIndentedString(pnLChart)).append("\n");
		sb.append("    equity: ").append(toIndentedString(equity)).append("\n");
		sb.append("    totalProfit: ").append(toIndentedString(totalProfit)).append("\n");
		sb.append("    sharpeRatio: ").append(toIndentedString(sharpeRatio)).append("\n");
		sb.append("    sortinoRatio: ").append(toIndentedString(sortinoRatio)).append("\n");
		sb.append("    calmarRatio: ").append(toIndentedString(calmarRatio)).append("\n");
		sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

