/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RebalancesViewModel
 */

public class RebalancesViewModel
{
	@SerializedName("rebalances")
	private List<RebalancingModel> rebalances = null;

	@SerializedName("total")
	private Integer total = null;

	public RebalancesViewModel rebalances(List<RebalancingModel> rebalances) {
		this.rebalances = rebalances;
		return this;
	}

	public RebalancesViewModel addRebalancesItem(RebalancingModel rebalancesItem) {
		if (this.rebalances == null) {
			this.rebalances = new ArrayList<RebalancingModel>();
		}
		this.rebalances.add(rebalancesItem);
		return this;
	}

	/**
	 * Get rebalances
	 *
	 * @return rebalances
	 **/
	@ApiModelProperty(value = "")
	public List<RebalancingModel> getRebalances() {
		return rebalances;
	}

	public void setRebalances(List<RebalancingModel> rebalances) {
		this.rebalances = rebalances;
	}

	public RebalancesViewModel total(Integer total) {
		this.total = total;
		return this;
	}

	/**
	 * Get total
	 *
	 * @return total
	 **/
	@ApiModelProperty(value = "")
	public Integer getTotal() {
		return total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RebalancesViewModel rebalancesViewModel = (RebalancesViewModel) o;
		return Objects.equals(this.rebalances, rebalancesViewModel.rebalances) &&
				Objects.equals(this.total, rebalancesViewModel.total);
	}

	@Override
	public int hashCode() {
		return Objects.hash(rebalances, total);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RebalancesViewModel {\n");

		sb.append("    rebalances: ").append(toIndentedString(rebalances)).append("\n");
		sb.append("    total: ").append(toIndentedString(total)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

