/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SignalTradingEvent
 */


public class SignalTradingEvent implements Parcelable
{
	@SerializedName("date")
	private DateTime date = null;

	@SerializedName("message")
	private String message = null;

	public SignalTradingEvent() {
	}

	public SignalTradingEvent date(DateTime date) {
		this.date = date;
		return this;
	}

	/**
	 * Get date
	 *
	 * @return date
	 **/
	@Schema(description = "")
	public DateTime getDate() {
		return date;
	}

	public void setDate(DateTime date) {
		this.date = date;
	}

	public SignalTradingEvent message(String message) {
		this.message = message;
		return this;
	}

	/**
	 * Get message
	 *
	 * @return message
	 **/
	@Schema(description = "")
	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SignalTradingEvent signalTradingEvent = (SignalTradingEvent) o;
		return Objects.equals(this.date, signalTradingEvent.date) &&
				Objects.equals(this.message, signalTradingEvent.message);
	}

	@Override
	public int hashCode() {
		return Objects.hash(date, message);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SignalTradingEvent {\n");

		sb.append("    date: ").append(toIndentedString(date)).append("\n");
		sb.append("    message: ").append(toIndentedString(message)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}


	public void writeToParcel(Parcel out, int flags) {
		out.writeValue(date);
		out.writeValue(message);
	}

	public static final Parcelable.Creator<SignalTradingEvent> CREATOR = new Parcelable.Creator<SignalTradingEvent>()
	{
		public SignalTradingEvent createFromParcel(Parcel in) {
			return new SignalTradingEvent(in);
		}

		public SignalTradingEvent[] newArray(int size) {
			return new SignalTradingEvent[size];
		}
	};

	public int describeContents() {
		return 0;
	}

	SignalTradingEvent(Parcel in) {
		date = (DateTime) in.readValue(DateTime.class.getClassLoader());
		message = (String) in.readValue(null);
	}
}
