/*
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;
import java.util.UUID;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * UploadResult
 */


public class UploadResult implements Parcelable
{
	@SerializedName("id")
	private UUID id = null;

	public UploadResult() {
	}

	public UploadResult id(UUID id) {
		this.id = id;
		return this;
	}

	/**
	 * Get id
	 *
	 * @return id
	 **/
	@Schema(description = "")
	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		UploadResult uploadResult = (UploadResult) o;
		return Objects.equals(this.id, uploadResult.id);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class UploadResult {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}


	public void writeToParcel(Parcel out, int flags) {
		out.writeValue(id);
	}

	public static final Parcelable.Creator<UploadResult> CREATOR = new Parcelable.Creator<UploadResult>()
	{
		public UploadResult createFromParcel(Parcel in) {
			return new UploadResult(in);
		}

		public UploadResult[] newArray(int size) {
			return new UploadResult[size];
		}
	};

	public int describeContents() {
		return 0;
	}

	UploadResult(Parcel in) {
		id = (UUID) in.readValue(UUID.class.getClassLoader());
	}
}
