/*
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * WalletsInfo
 */

public class WalletsInfo
{
	@SerializedName("wallets")
	private List<WalletInfo> wallets = null;

	public WalletsInfo wallets(List<WalletInfo> wallets) {
		this.wallets = wallets;
		return this;
	}

	public WalletsInfo addWalletsItem(WalletInfo walletsItem) {
		if (this.wallets == null) {
			this.wallets = new ArrayList<WalletInfo>();
		}
		this.wallets.add(walletsItem);
		return this;
	}

	/**
	 * Get wallets
	 *
	 * @return wallets
	 **/
	@ApiModelProperty(value = "")
	public List<WalletInfo> getWallets() {
		return wallets;
	}

	public void setWallets(List<WalletInfo> wallets) {
		this.wallets = wallets;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		WalletsInfo walletsInfo = (WalletsInfo) o;
		return Objects.equals(this.wallets, walletsInfo.wallets);
	}

	@Override
	public int hashCode() {
		return Objects.hash(wallets);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class WalletsInfo {\n");

		sb.append("    wallets: ").append(toIndentedString(wallets)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

