/*
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * WalletInvestmentPrograms
 */

public class WalletInvestmentPrograms
{
	@SerializedName("investmentPrograms")
	private List<WalletInvestmentProgram> investmentPrograms = null;

	public WalletInvestmentPrograms investmentPrograms(List<WalletInvestmentProgram> investmentPrograms) {
		this.investmentPrograms = investmentPrograms;
		return this;
	}

	public WalletInvestmentPrograms addInvestmentProgramsItem(WalletInvestmentProgram investmentProgramsItem) {
		if (this.investmentPrograms == null) {
			this.investmentPrograms = new ArrayList<WalletInvestmentProgram>();
		}
		this.investmentPrograms.add(investmentProgramsItem);
		return this;
	}

	/**
	 * Get investmentPrograms
	 *
	 * @return investmentPrograms
	 **/
	@ApiModelProperty(value = "")
	public List<WalletInvestmentProgram> getInvestmentPrograms() {
		return investmentPrograms;
	}

	public void setInvestmentPrograms(List<WalletInvestmentProgram> investmentPrograms) {
		this.investmentPrograms = investmentPrograms;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		WalletInvestmentPrograms walletInvestmentPrograms = (WalletInvestmentPrograms) o;
		return Objects.equals(this.investmentPrograms, walletInvestmentPrograms.investmentPrograms);
	}

	@Override
	public int hashCode() {
		return Objects.hash(investmentPrograms);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class WalletInvestmentPrograms {\n");

		sb.append("    investmentPrograms: ").append(toIndentedString(investmentPrograms)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

